// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrpjuhbamxpssynfxscc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ycGp1aGJhbXhwc3N5bmZ4c2NjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMDQyODIsImV4cCI6MjA2OTU4MDI4Mn0.-bAhfy6TtGcqvNBqTS7orpiH3HXX0u9U2r3D8vQR1Jk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});